### ISSUE TITLE
Add extraction of notes

### ISSUE THREAD

**Issue by kabili207** [neobooru/neo-scraper#10]
Many boorus support notes for translation of inline text. It would be very useful to be able to extract this.

Examples (safe):
 https://gelbooru.com/index.php?page=post&s=view&id=6225495
 https://danbooru.donmai.us/posts/4924490

**Comment by neobooru** [comment]
Added, at least for those two sites.

Do you have links to posts on other boorus too? I personally didn't really find a way to actually find posts that have notes attached to them, so it's hard to test that.

**Comment by kabili207** [comment]
I'm looking around for more. Danbooru was easy since they have a [page to view all notes](https://danbooru.donmai.us/notes) right in the nav header. Sites based on gelbooru (like rule34 and safebooru) should be the same.

**Comment by kabili207** [comment]
Konachan: https://konachan.com/note
Yandere: https://yande.re/note
Sankaku: https://chan.sankakucomplex.com/note/index

Shimmie2 supposedly supports it via an extension, Rule34 Phael doesn't seem to have it enabled and I can't find any other booru that uses shimmie2. [Source may be of help](https://github.com/shish/shimmie2/blob/master/ext/notes/theme.php)

**Comment by neobooru** [comment]
Okay I think this has been implemented for the most part. SzuruChrome will get an update sometime later. There might be some bugs here and there so feel free to create a new issue for those. If I missed anything else then feel free to reopen this.
