### ISSUE TITLE
FurAffinity: add artist as a tag

### ISSUE THREAD

**Issue by FlipperLP** [neobooru/neo-scraper#12]
The user that submitted the art should be added as an artist tag in szuru.

**Comment by neobooru** [comment]
I've seen a lot of cases where a user commissions a piece and then uploads it. In those cases the user that submitted it isn't the actual artist. How would you want to handle this?

**Comment by FlipperLP** [comment]
I mean… I would add it as a tag, as the piece will be brought into a connection with the commissioner or the artist either way.
Also, the tags are already quite bad on FA so adding the "artist" additionally is really not lowering the quality of the tags. But in the end, it's up to you.

**Comment by neobooru** [comment]
Added in 73ffee047e2281b93753cfdb359a6f9a4c61d2ea, will be updated in SzuruChrome sometime soon.
neo-scraper currently forces all tags to be lowercase, if this is a problem for you then please open a new issue with a feature request to change this. For my use-cases this is no problem, but idk how others feel about that.
