### ISSUE TITLE
Update Twitter Engine

### ISSUE THREAD

**Issue by robobenklein** [neobooru/neo-scraper#8]
I am not super familiar with how to set up a test environment for this module, but I am willing to do some coding once I know how.

Right now it appears the Twitter engine is using some selectors which I don't think apply in the latest twitter site frontends, and in fact I don't believe any CSS classes are stable for usage.

The best solution I could come up with for a working image selector is to use the following xpath:

```js
'//article//a[@role="link"]//div[@data-testid="tweetPhoto"]//img'
// like so:
var xpath = function(xpathToExecute){
  var result = [];
  var nodesSnapshot = document.evaluate(xpathToExecute, document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null );
  for ( var i=0 ; i < nodesSnapshot.snapshotLength; i++ ){
    result.push( nodesSnapshot.snapshotItem(i) );
  }
  return result;
}
xpath('//article//a[@role="link"]//div[@data-testid="tweetPhoto"]//img')
```

Which results in a decent / more useful image selection than the fallback:

![image](https://user-images.githubusercontent.com/5423266/124503111-ddbc4900-dd92-11eb-8df8-6951b0185f60.png)

**Comment by neobooru** [comment]
Tbh I had already given up on twitter, but if there is interest in a working version then I guess I'll look at it.
As for the xpath, if I'm not mistaken something like 
```js
document.querySelectorAll("article a[role='link'] div[data-testid='tweetPhoto'] img");
```
achieves the same results, or am I missing something?

Two things it doesn't catch are 1. animated content (gifs/video) and 2. fullscreen content. I would probably implement those in a separate query and then merge the results. If you want you could look at that too, but if not then I'll look at it sometime.

As for a test environment I simply use SzuruChrome with `yarn link neo-scraper` in the SzuruChrome root dir. For this to work you first need to call `yarn link` in the neo-scraper root dir. I guess you could also use the jest tests, but imo its easier to debug the DOM in a fully fledged browser.
